global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.105:9113']
        labels:
          group: 'my_stand'

  - job_name: 'node_exporter_clients'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.105:9100']

  - job_name: postgresql
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.105:9187']
        labels:
          alias: postgres

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://192.168.0.105    # Target to probe with http.
        - http://192.168.0.105:8080   # Target to probe with https..
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.105:9115  # The blackbox exporter's real hostname:port.

  - job_name: php-fpm
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.105:9253']
        labels:
          alias: php-fpm

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "alert.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.0.109:9093']
